# Generated by Django 4.2.6 on 2024-02-11 03:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
